# Generated by Django 3.0.2 on 2020-03-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_comment'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(blank=True, null=True, to='movies.Movies'),
        ),
    ]
