# Generated by Django 3.0.2 on 2020-03-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_comment'),
        ('accounts', '0002_user_watch_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_added_to_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_on_list', to='movies.Movies')),
                ('user_who_add_to_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to='accounts.User')),
            ],
        ),
    ]
