# Generated by Django 3.0.2 on 2020-03-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_comment'),
        ('accounts', '0003_userwatchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(blank=True, to='movies.Movies'),
        ),
    ]
