# Generated by Django 3.0.2 on 2020-03-17 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20200317_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchlist',
            name='user_who_add_to_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
