# Generated by Django 3.0.2 on 2020-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='nation',
        ),
        migrations.AddField(
            model_name='actor',
            name='biography',
            field=models.TextField(null=True),
        ),
    ]
