# Generated by Django 3.0.2 on 2020-03-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movies_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=256),
        ),
    ]
