# Generated by Django 3.0.2 on 2020-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20200313_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrater',
            name='user_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
